# Base configs
baseurl: "bmterra.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Bruno Terra"
subtitle: ""
author: "Bruno Terra"
header:
 title: "Photography"
 subtitle: "by Bruno Terra"
footer:
 name: ""
 bio: ""
 github: ""
web_design: "BT"
social_urls:
  twitter: "https://www.twitter.com/nakiski"
  instagram: "https://www.instagram.com/bmterra"
  github: "https://www.github.com/bmterra"
